project:
  type: website
  output-dir: docs

website:
  title: "Applied Econometrics"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - text: Recitations
        menu: 
          - recitations/recitation-1.ipynb
          - recitations/recitation-2.qmd
          - recitations/recitation-3.ipynb
          - recitations/recitation-4.ipynb
      - text: Models
        menu:
          - models/search-model.ipynb
          - models/entry-exit.ipynb
          - models/savings.ipynb
      - text: Assignments
        menu:
          - assignments/Assignment-1.ipynb
          - assignments/Assignment-2.ipynb
          - assignments/Assignment-3.ipynb
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



